### ISSUE TITLE
window positions should have position:fixed

### ISSUE THREAD

**Issue by Qazzian** [julianxhokaxhiu/chrome-link-revealer#1]
Hey,

I was just trying this out and It works really well as a tooltip.
But if I set the "relative to window" option then the tooltip is placed on the edge of the website document instead of the edge of the window causing it to be out of view for larger web pages. 

I can fix it on individual pages by adding a css rule in the dev console

``` css
.ui-tooltip, .qtip { position:fixed; } 
```

Here is a quick example of the problem

![screen shot 2014-01-30 at 12 20 40](https://f.cloud.github.com/assets/326569/2039792/204ef86c-89a9-11e3-8d13-ab36af3dd498.png)

**Comment by julianxhokaxhiu** [comment]
Hi, thanks for the report.

I've pushed the fix to the master tree :) I'll update the extension too right now!

**Comment by Qazzian** [comment]
cool. 
I've got the update now and it works well.

Thanks for the quick turn around.
